return {}
-- return {
-- 	"ThePrimeagen/harpoon",
-- 	branch = "harpoon2",
-- 	-- lazy = true,
-- 	event = "VimEnter",
-- 	dependencies = { "nvim-lua/plenary.nvim" },
-- 	config = function()
-- 		local harpoon = require("harpoon"):setup()
-- 		-- local extensions = require("harpoon.extensions")
-- 		vim.keymap.set("n", "<leader>n", function()
-- 			harpoon:list():add()
-- 		end)
-- 		vim.keymap.set("n", "<leader>m", function()
-- 			harpoon.ui:toggle_quick_menu(harpoon:list())
-- 		end)
--
-- 		vim.keymap.set("n", "<C-j>", function()
-- 			harpoon:list():select(1)
-- 		end)
-- 		vim.keymap.set("n", "<C-k>", function()
-- 			harpoon:list():select(2)
-- 		end)
-- 		vim.keymap.set("n", "<C-n>", function()
-- 			harpoon:list():select(3)
-- 		end)
-- 		vim.keymap.set("n", "<C-m>", function()
-- 			harpoon:list():select(4)
-- 		end)
-- 		vim.keymap.set("n", "<leader>l", function()
-- 			harpoon:list():select(1)
-- 		end)
-- 		vim.keymap.set("n", "<leader>l", function()
-- 			harpoon:list():next()
-- 		end)
-- 		vim.keymap.set("n", "<leader>;", function()
-- 			harpoon:list():prev()
-- 		end)
-- 	end,
-- }
